server:
  port: ${PORT:0}
spring:
  application:
    name: service-celulares
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    service_url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
ribbon:
 ConnectTimeout: 3000
 ReadTimeout: 10000
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 20000